name: Ensure pnpm
description: Ensure pnpm is available via Corepack fallback with retry (composite action cannot invoke other actions in steps for reliability here).
runs:
  using: composite
  steps:
    - name: Provision pnpm via Corepack (retry)
      shell: bash
      run: |
        set -euo pipefail
        TARGET_VERSION="10.14.0"
        if command -v pnpm >/dev/null 2>&1; then
          echo "pnpm already present: $(pnpm -v)"; exit 0; fi
        echo "Provisioning pnpm@${TARGET_VERSION} via Corepack"
        corepack enable || true
        for i in 1 2 3; do
          echo "Attempt $i: corepack prepare pnpm@${TARGET_VERSION} --activate";
          if corepack prepare pnpm@${TARGET_VERSION} --activate; then
            break
          fi
          sleep $((i*2))
        done
        if ! command -v pnpm >/dev/null 2>&1; then
          echo '::error::Failed to provision pnpm after retries'; exit 1; fi
        pnpm -v
    - name: Sanitize npm registries
      shell: bash
      run: |
        set -euo pipefail
        echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        pnpm config set registry https://registry.npmjs.org/
        npm config set registry https://registry.npmjs.org/
        pnpm config delete @jsr:registry || true
        npm config delete @jsr:registry || true
        pnpm config set fetch-retries 4
        pnpm config set network-timeout 600000
