name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use pnpm version from package.json: "packageManager": "pnpm@..."
      - name: Setup pnpm (use packageManager version)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Show pnpm version
        run: pnpm -v

      # Install all workspace dependencies
      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile=false

      # 👇 Make sure the AWS SDK is installed specifically in the fun-launch package
      - name: Add @aws-sdk/client-s3 to fun-launch package
        run: pnpm -r --filter "@meteora-invent/scaffold/fun-launch" add @aws-sdk/client-s3

      # Optional: show that the dep is present in that package now
      - name: List deps in fun-launch
        run: pnpm -r --filter "@meteora-invent/scaffold/fun-launch" list @aws-sdk/client-s3 --depth 0

      - name: Type check
        run: pnpm exec tsc --noEmit --project tsconfig.typecheck.json

      - name: Build
        run: pnpm build
