name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm matching your package.json "packageManager": "pnpm@10.14.0"
      # NOTE: Do NOT set a "version" here to avoid conflicts.
      - name: Setup pnpm (use packageManager version)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Show pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      # Ensure AWS SDK v3 S3 client is present at build time (without changing your package.json)
      - name: Ensure @aws-sdk/client-s3 is available
        run: pnpm add -w --no-save @aws-sdk/client-s3

      - name: Type check
        run: pnpm exec tsc --noEmit --project tsconfig.typecheck.json

      - name: Build
        run: pnpm build
