name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Setup pnpm using the version from package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Show pnpm version
        run: pnpm -v

      # Install workspace dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      # ✅ Force install required deps in fun-launch
      - name: Install AWS SDK + Node types in fun-launch
        run: |
          pnpm add @aws-sdk/client-s3 @aws-sdk/s3-request-presigner @types/node --filter @meteora-invent/scaffold/fun-launch

      # Double-check packages are there
      - name: Verify installed packages
        run: pnpm list @aws-sdk/client-s3 @aws-sdk/s3-request-presigner @types/node --filter @meteora-invent/scaffold/fun-launch --depth 0

      # Type check
      - name: Type check
        run: pnpm exec tsc --noEmit --project tsconfig.typecheck.j
