name: Claim Partner Fees

on:
  workflow_dispatch:
    inputs:
      pool:
        description: "Pool public key to claim from"
        required: true
        type: string

permissions:
  contents: read

jobs:
  claim:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: 'false'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ensure pnpm is available on PATH (works even if the pnpm action fails)
      - name: Enable corepack & activate pnpm 10.14.0
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
          pnpm -v

      # Install ONLY inside the studio folder to avoid fun-launch mismatch
      - name: Install studio deps only
        run: pnpm -C studio install --no-frozen-lockfile

      - name: Run claim_trading_fee script
        working-directory: studio
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY_B58: ${{ secrets.PRIVATE_KEY_B58 }}
        run: pnpm dlx tsx src/scripts/dbc/claim_trading_fee.ts ${{ github.event.inputs.pool }}
