name: Claim Partner Fees

on:
  workflow_dispatch:
    inputs:
      base_mint:
        description: "Base mint (your token mint, e.g. 8Gu76ci6eqLyVgKMjigyvXCczBVL6dkfrfJewbdbhpYQ)"
        required: true
        type: string
      quote_mint:
        description: "Quote mint (WSOL: So11111111111111111111111111111111111111112, or USDC mint)"
        required: true
        type: string

permissions:
  contents: read

# 🚫 Critical: run EVERY step from /studio so the root/fun-launch never gets touched
defaults:
  run:
    working-directory: studio

jobs:
  claim:
    runs-on: ubuntu-latest
    # 🚫 Kill pnpm's CI frozen lockfile behavior everywhere in this job
    env:
      CI: 'false'
      PNPM_CONFIG_FROZEN_LOCKFILE: 'false'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ensure pnpm 10.14.0 is on PATH (matches your packageManager)
      - name: Enable corepack & activate pnpm 10.14.0
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
          pnpm -v

      # ✅ Install ONLY studio deps (root is never touched)
      - name: Install deps (studio only)
        run: pnpm install --no-frozen-lockfile

      # Build a keypair.json from your base58 secret (what your script expects)
      - name: Write keypair.json from PRIVATE_KEY_B58
        env:
          PK_B58: ${{ secrets.PRIVATE_KEY_B58 }}
        run: |
          npx -y -p bs58 node -e "const fs=require('fs');const bs58=require('bs58');const s=process.env.PK_B58?.trim();if(!s)throw new Error('Missing PRIVATE_KEY_B58');const arr=Array.from(bs58.decode(s));fs.writeFileSync('keypair.json', JSON.stringify(arr));"

      # Sanity: show the target file exists with the exact casing
      - name: List dbc scripts
        run: ls -la src/scripts/dbc

      # Run your existing script with the CLI flags it expects
      - name: Run claim_trading_fee.ts
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          pnpm exec tsx src/scripts/dbc/claim_trading_fee.ts \
            --rpcUrl="$RPC_URL" \
            --keypairFilePath="$PWD/keypair.json" \
            --baseMint="${{ github.event.inputs.base_mint }}" \
            --quoteMint="${{ github.event.inputs.quote_mint }}"
