name: Claim Leftover SOL (DBC)

on:
  workflow_dispatch:
    inputs:
      BASE_MINTS:
        description: 'Comma-separated base mints to check/claim'
        required: true
      LEFTOVER_RECEIVER:
        description: 'Override leftover receiver (optional; defaults to signer)'
        required: false
        default: ''

jobs:
  claim-leftovers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build (optional)
        run: pnpm -w build || echo "Skip build"

      - name: Run leftover claim
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          # Provide ONE of the following (base64 is safest):
          PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY_BASE64 }}
          PRIVATE_KEY_B58: ${{ secrets.PRIVATE_KEY_B58 }}
          PRIVATE_KEY_JSON: ${{ secrets.PRIVATE_KEY_JSON }}
          # Inputs
          BASE_MINTS: ${{ github.event.inputs.BASE_MINTS }}
          LEFTOVER_RECEIVER: ${{ github.event.inputs.LEFTOVER_RECEIVER }}
        run: |
          echo "Running leftover claim..."
          npx -y tsx studio/src/scripts/dbc/claim_leftovers.ts
