name: Claim Partner Fees

on:
  workflow_dispatch:
    inputs:
      base_mint:
        description: "Base mint (your token mint, e.g. 8Gu76c...hpYQ)"
        required: true
        type: string
      quote_mint:
        description: "Quote mint (e.g. WSOL or USDC mint)"
        required: true
        type: string

permissions:
  contents: read

defaults:
  run:
    working-directory: studio   # <- all commands run inside /studio

jobs:
  claim:
    runs-on: ubuntu-latest
    env:
      CI: 'false'                         # pnpm won't auto-freeze lockfile
      PNPM_CONFIG_FROZEN_LOCKFILE: 'false'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ensure pnpm is on PATH and matches your package.json
      - name: Enable corepack & activate pnpm 10.14.0
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
          pnpm -v

      # Install ONLY the studio workspace deps (no root, no fun-launch)
      - name: Install deps (studio only)
        run: pnpm install --no-frozen-lockfile

      # Build a Solana keypair.json from PRIVATE_KEY_B58 (no repo changes)
      - name: Write keypair.json from PRIVATE_KEY_B58
        env:
          PK_B58: ${{ secrets.PRIVATE_KEY_B58 }}
        run: |
          npx -y -p bs58 node -e "const fs=require('fs');const bs58=require('bs58');const s=process.env.PK_B58?.trim();if(!s)throw new Error('Missing PRIVATE_KEY_B58');const arr=Array.from(bs58.decode(s));fs.writeFileSync('keypair.json', JSON.stringify(arr));"

      # Run your existing script with the flags it expects
      - name: Run claim_trading_fee.ts
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          pnpm exec tsx src/scripts/dbc/claim_trading_fee.ts \
            --rpcUrl="$RPC_URL" \
            --keypairFilePath="$PWD/keypair.json" \
            --baseMint="${{ github.event.inputs.base_mint }}" \
            --quoteMint="${{ github.event.inputs.quote_mint }}"
