name: Claim Partner Fees

on:
  workflow_dispatch:

jobs:
  claim-partner-fees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js first so pnpm stays in PATH
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install pnpm after Node setup so it doesn't get overwritten
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies (cached)
        run: pnpm install --frozen-lockfile

      - name: Decode PK_B58 to keypair.json
        run: |
          npx -y -p bs58@4 node -e "
            const fs = require('fs');
            const bs58 = require('bs58');
            const s = process.env.PK_B58?.trim();
            if (!s) throw new Error('Missing PRIVATE_KEY_B58');
            const arr = Array.from(bs58.decode(s));
            fs.writeFileSync('keypair.json', JSON.stringify(arr));
          "
        env:
          PK_B58: ${{ secrets.PK_B58 }}

      - name: Run claim partner fees script
        run: pnpm claim:partner-fees

      - name: Clean up keypair.json
        run: rm -f keypair.json
