name: Claim Partner Fees

on:
  workflow_dispatch:

jobs:
  claim-partner-fees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # ⬇ Replace the old decode step with this one
      - name: Decode PK_B58 to full keypair.json
        run: |
          npx -y -p @solana/web3.js@1.98.2 -p bs58@4 node -e "
            const fs = require('fs');
            const b = require('bs58');
            const { Keypair } = require('@solana/web3.js');

            const s = (process.env.PK_B58 || process.env.PRIVATE_KEY_B58 || '').trim();
            if (!s) throw new Error('Missing PK_B58 or PRIVATE_KEY_B58');

            const decode = (b && b.decode) ? b.decode : (b.default && b.default.decode);
            if (typeof decode !== 'function') throw new Error('bs58.decode not available');

            const secret = decode(s); // 32 or 64 bytes
            if (secret.length !== 32 && secret.length !== 64) {
              throw new Error('Decoded key length is ' + secret.length + ' bytes; expected 32 or 64');
            }

            const kp = Keypair.fromSecretKey(secret);
            fs.writeFileSync('keypair.json', JSON.stringify(Array.from(kp.secretKey)));
            console.log('Public key:', kp.publicKey.toBase58());
          "
        env:
          PK_B58: ${{ secrets.PK_B58 }}
          PRIVATE_KEY_B58: ${{ secrets.PRIVATE_KEY_B58 }}

      - name: Assert BASE_MINTS is set
        run: |
          if [ -z "${BASE_MINTS}" ]; then
            echo "::error::BASE_MINTS secret is missing. Set Settings > Secrets > Actions > BASE_MINTS to a comma-separated list of your DBC base mint addresses.";
            exit 1
          fi
          echo "BASE_MINTS=${BASE_MINTS}"
        env:
          BASE_MINTS: ${{ secrets.BASE_MINTS }}

      - name: Run claim trading fee script
        run: |
          echo "Using BASE_MINTS=${BASE_MINTS}"
          npx -y -p tsx tsx studio/src/scripts/dbc/claim_trading_fee_all.ts --config ./studio/config/dbc_config.jsonc
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          BASE_MINTS: ${{ secrets.BASE_MINTS }}

      - name: Clean up keypair.json
        run: rm -f keypair.json
