name: Claim All Partner Fees

on:
  workflow_dispatch:
    inputs:
      pools:
        description: "Comma-separated pool public keys (e.g. A1..,B2..,C3..)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  claim:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: 'false'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install studio deps only
        run: pnpm -w --filter "./studio..." install --no-frozen-lockfile

      - name: Claim partner fees (many)
        working-directory: studio
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY_B58: ${{ secrets.PRIVATE_KEY_B58 }}
          POOLS: ${{ github.event.inputs.pools }}
        run: pnpm dlx tsx src/scripts/dbc/claim_many.ts
