name: Claim Partner Fees

on:
  workflow_dispatch:
    inputs:
      pool:
        description: "Pool public key to claim from"
        required: true
        type: string

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run claim_trading_fee script
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY_B58: ${{ secrets.PRIVATE_KEY_B58 }}
        working-directory: studio
        run: pnpm dlx tsx src/scripts/dbc/claim_trading_fee.ts ${{ github.event.inputs.pool }}
