name: Claim DBC Bonding-Curve Leftovers

on:
  workflow_dispatch: {}         # run manually from the Actions tab
  schedule:
    - cron: "15 * * * *"        # run hourly at :15 (UTC)

jobs:
  claim-leftovers:
    runs-on: ubuntu-latest

    # All env is taken from repo/org Secrets (Settings → Secrets and variables → Actions)
    # REQUIRED:
    #   - RPC_URL
    #   - BASE_MINTS            (comma-separated list of base mint addresses)
    #   - DBC_CONFIG_KEYS       (comma-separated list of config keys)
    #   - LEFTOVER_RECEIVER     (Solana pubkey to receive leftovers)
    #   - *one* of PK_B58 or PRIVATE_KEY_B58 (wallet)
    # OPTIONAL:
    #   - DBC_PROGRAM_IDS       (comma-separated program IDs; leave empty to use SDK defaults)
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      BASE_MINTS: ${{ secrets.BASE_MINTS }}
      DBC_CONFIG_KEYS: ${{ secrets.DBC_CONFIG_KEYS }}
      DBC_PROGRAM_IDS: ${{ secrets.DBC_PROGRAM_IDS }}
      LEFTOVER_RECEIVER: ${{ secrets.LEFTOVER_RECEIVER }}
      PK_B58: ${{ secrets.PK_B58 }}
      PRIVATE_KEY_B58: ${{ secrets.PRIVATE_KEY_B58 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Validate required secrets
        shell: bash
        run: |
          set -euo pipefail

          require() {
            local name="$1"
            if [ -z "${!name:-}" ]; then
              echo "::error title=Missing secret::$name is required but not set"
              exit 1
            fi
          }

          # Required:
          require RPC_URL
          require BASE_MINTS
          require DBC_CONFIG_KEYS
          require LEFTOVER_RECEIVER

          # Wallet: one of PK_B58 or PRIVATE_KEY_B58 must be present
          if [ -z "${PK_B58:-}" ] && [ -z "${PRIVATE_KEY_B58:-}" ]; then
            echo "::error title=Missing wallet secret::Provide PK_B58 (preferred) or PRIVATE_KEY_B58"
            exit 1
          fi

          # Optional DBC_PROGRAM_IDS — warn if missing (SDK defaults will be used)
          if [ -z "${DBC_PROGRAM_IDS:-}" ]; then
            echo "::notice title=Optional::DBC_PROGRAM_IDS not set; using SDK defaults (if your script supports it)."
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Optional typecheck (skip emit)
      - name: Typecheck
        run: pnpm exec tsc --noEmit

      # Run the script directly with ts-node (no build needed)
      - name: Claim leftovers
        run: pnpm dlx ts-node studio/src/scripts/dbc/claim_leftovers.ts
