name: Create Raydium Platform
on:
  workflow_dispatch: {}

jobs:
  setup-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # ✅ Enable pnpm bundled with Node via Corepack
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install

      - name: Run create-platform script
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          RAYDIUM_PLATFORM_AUTHORITY_SECRET: ${{ secrets.RAYDIUM_PLATFORM_AUTHORITY_SECRET }}
          RAYDIUM_SHARE_FEE_BPS: "175"
          RAYDIUM_CREATION_FEE_LAMPORTS: "25000000"
          RAYDIUM_MIGRATE_SPLIT_PLATFORM_BPS: "0"
          RAYDIUM_MIGRATE_SPLIT_CREATOR_BPS: "10000"
          RAYDIUM_MIGRATE_SPLIT_BURN_BPS: "0"
          RAYDIUM_LOCK_LP: "false"
        run: pnpm dlx tsx scaffolds/fun-launch/scripts/raydium/create-platform.ts
