name: Create Raydium Platform
on:
  workflow_dispatch: {}

jobs:
  setup-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ✅ This installs pnpm and adds it to PATH
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true   # runs "pnpm install" for you

      - name: Show pnpm version (debug)
        run: pnpm -v

      - name: Run create-platform script
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          RAYDIUM_PLATFORM_AUTHORITY_SECRET: ${{ secrets.RAYDIUM_PLATFORM_AUTHORITY_SECRET }}
          RAYDIUM_SHARE_FEE_BPS: "175"
          RAYDIUM_CREATION_FEE_LAMPORTS: "25000000"
          RAYDIUM_MIGRATE_SPLIT_PLATFORM_BPS: "0"
          RAYDIUM_MIGRATE_SPLIT_CREATOR_BPS: "10000"
          RAYDIUM_MIGRATE_SPLIT_BURN_BPS: "0"
          RAYDIUM_LOCK_LP: "false"
        run: pnpm dlx tsx scaffolds/fun-launch/scripts/raydium/create-platform.ts
